import type { UploadResult } from '../types/main';
import {
  extractCompressedUuid,
  extractOriginalUploadUuid,
  extractPairedVideoUuid,
  extractPosterUuid,
} from './uploadKeys';
import { getAttachmentUploadPolicy } from './uploadPolicy';
import { getAttachmentDetailsByRoteId, upsertAttachmentsByOriginalKey } from '../utils/dbMethods';
import {
  MAX_BATCH_SIZE,
  inferAttachmentMediaKind,
  isImageContentType,
  isVideoContentType,
  mergeUniqueRoteAttachmentDetails,
  validateContentType,
  validateFileSize,
  validateRoteAttachmentDetails,
} from '../utils/fileValidation';
import { checkObjectExists } from '../utils/r2';
import type { FinalizeAttachmentInput } from './types';
import { requireStorageAvailable } from './types';
import attachmentErrors from './errorCodes.json';
import { ensureHeicBrowserCover } from './heicBrowserCover';
import { assertLivePhotoFinalizeBatch } from './livePhotoFinalize';
import { finalizeInputIncludesVideo, isHeicLikeUpload } from './uploadMedia';
import { detectStoredImageContentTypeByKey } from './storedImageContent';

export type FinalizeAttachmentDependencies = {
  checkObjectExists: typeof checkObjectExists;
  detectStoredImageContentTypeByKey: typeof detectStoredImageContentTypeByKey;
  ensureHeicBrowserCover: typeof ensureHeicBrowserCover;
  getAttachmentDetailsByRoteId: typeof getAttachmentDetailsByRoteId;
  getAttachmentUploadPolicy: typeof getAttachmentUploadPolicy;
  requireStorageAvailable: typeof requireStorageAvailable;
  upsertAttachmentsByOriginalKey: typeof upsertAttachmentsByOriginalKey;
};

const defaultDependencies: FinalizeAttachmentDependencies = {
  checkObjectExists,
  detectStoredImageContentTypeByKey,
  ensureHeicBrowserCover,
  getAttachmentDetailsByRoteId,
  getAttachmentUploadPolicy,
  requireStorageAvailable,
  upsertAttachmentsByOriginalKey,
};

function assertFinalizeInput(
  attachments: FinalizeAttachmentInput[] | undefined
): asserts attachments is FinalizeAttachmentInput[] {
  if (!attachments || !Array.isArray(attachments) || attachments.length === 0) {
    throw new Error(attachmentErrors.attachmentsRequired);
  }
  if (attachments.length > MAX_BATCH_SIZE) {
    throw new Error(attachmentErrors.attachmentBatchLimitExceeded);
  }
}

function validateAttachmentPayload(item: FinalizeAttachmentInput, maxVideoUploadSizeMB: number) {
  if (item.mimetype) {
    validateContentType(item.mimetype);
    validateFileSize(item.size, item.mimetype, maxVideoUploadSizeMB);
  }
  if (item.mediaKind === 'livePhoto' || item.pairedVideoKey) {
    if (!isImageContentType(item.mimetype))
      throw new Error(attachmentErrors.livePhotoOriginalNotImage);
    validateContentType(item.pairedVideoMimetype);
    if (!isVideoContentType(item.pairedVideoMimetype))
      throw new Error(attachmentErrors.livePhotoPairedVideoNotVideo);
    validateFileSize(item.pairedVideoSize, item.pairedVideoMimetype, maxVideoUploadSizeMB);
  }
}

async function collectValidAttachments(
  attachments: FinalizeAttachmentInput[],
  objectExists: typeof checkObjectExists
) {
  const validationErrors: string[] = [];
  const validAttachments: FinalizeAttachmentInput[] = [];
  for (const item of attachments) {
    const mediaKind = inferAttachmentMediaKind({
      mediaKind: item.mediaKind,
      mimetype: item.mimetype,
      compressedKey: item.compressedKey,
      posterKey: item.posterKey,
      pairedVideoKey: item.pairedVideoKey,
      key: item.originalKey,
    });
    const normalizedAttachment = { ...item };
    const originalExists = await objectExists(item.originalKey);
    if (!originalExists) {
      validationErrors.push(
        attachmentErrors.originalFileNotFoundPrefix + item.originalKey + ':' + item.uuid
      );
      continue;
    }

    const originalUuid = extractOriginalUploadUuid(item.originalKey);
    if (!originalUuid || originalUuid !== item.uuid) {
      validationErrors.push(attachmentErrors.uuidMismatchPrefix + item.originalKey);
      continue;
    }
    if (mediaKind === 'video' && normalizedAttachment.compressedKey) {
      validationErrors.push(attachmentErrors.videoCompressedKeyForbiddenPrefix + item.originalKey);
      continue;
    }
    if ((mediaKind === 'image' || mediaKind === 'livePhoto') && normalizedAttachment.posterKey) {
      normalizedAttachment.posterKey = undefined;
    }
    // Live Photo stills are always selected or generated by the server. Ignore
    // legacy client-provided .webp keys, which may contain JPEG bytes.
    if (mediaKind === 'livePhoto') {
      normalizedAttachment.compressedKey = undefined;
    }
    if (mediaKind === 'image' && normalizedAttachment.compressedKey) {
      const compressedExists = await objectExists(normalizedAttachment.compressedKey);
      const compressedUuid = extractCompressedUuid(normalizedAttachment.compressedKey);
      if (!compressedExists || !compressedUuid || originalUuid !== compressedUuid) {
        validationErrors.push(
          attachmentErrors.compressedFileInvalidPrefix + normalizedAttachment.compressedKey
        );
        normalizedAttachment.compressedKey = undefined;
      }
    }
    if (mediaKind === 'livePhoto') {
      if (!normalizedAttachment.pairedVideoKey) {
        validationErrors.push(
          attachmentErrors.livePhotoPairedVideoMissingPrefix + item.originalKey
        );
        continue;
      }
      const pairedVideoExists = await objectExists(normalizedAttachment.pairedVideoKey);
      const pairedVideoUuid = extractPairedVideoUuid(normalizedAttachment.pairedVideoKey);
      if (!pairedVideoExists || !pairedVideoUuid || originalUuid !== pairedVideoUuid) {
        validationErrors.push(
          attachmentErrors.livePhotoPairedVideoInvalidPrefix + normalizedAttachment.pairedVideoKey
        );
        continue;
      }
    } else if (normalizedAttachment.pairedVideoKey) {
      validationErrors.push(attachmentErrors.pairedVideoLivePhotoOnlyPrefix + item.originalKey);
      continue;
    }
    if (mediaKind === 'video' && normalizedAttachment.posterKey) {
      const posterExists = await objectExists(normalizedAttachment.posterKey);
      const posterUuid = extractPosterUuid(normalizedAttachment.posterKey);
      if (!posterExists || !posterUuid || originalUuid !== posterUuid) {
        validationErrors.push(
          attachmentErrors.posterFileInvalidPrefix + normalizedAttachment.posterKey
        );
        normalizedAttachment.posterKey = undefined;
      }
    }
    if (!mediaKind) {
      validationErrors.push(attachmentErrors.attachmentMediaUnsupportedPrefix + item.originalKey);
      continue;
    }
    validAttachments.push(normalizedAttachment);
  }

  if (validAttachments.length === 0) {
    const message =
      validationErrors.length === 1
        ? validationErrors[0]
        : attachmentErrors.attachmentValidationErrorsPrefix + validationErrors.join(';');
    throw new Error(message || attachmentErrors.attachmentValidationFailed);
  }
  return validAttachments;
}

function toUploadResult(urlPrefix: string, item: FinalizeAttachmentInput): UploadResult {
  const mediaKind = inferAttachmentMediaKind({
    mediaKind: item.mediaKind,
    mimetype: item.mimetype || null,
    compressedKey: item.compressedKey,
    posterKey: item.posterKey,
    pairedVideoKey: item.pairedVideoKey,
  });
  const pairedVideoUrl =
    mediaKind === 'livePhoto' && item.pairedVideoKey ? urlPrefix + '/' + item.pairedVideoKey : null;
  const details: any = {
    size: item.size || 0,
    mimetype: item.mimetype || null,
    mediaKind,
    mtime: new Date().toISOString(),
    key: item.originalKey,
  };
  if (item.compressedKey) details.compressKey = item.compressedKey;
  if (item.posterKey) details.posterKey = item.posterKey;
  if (pairedVideoUrl && item.pairedVideoKey) {
    details.pairedVideoKey = item.pairedVideoKey;
    details.pairedVideoUrl = pairedVideoUrl;
    details.pairedVideoMimetype = item.pairedVideoMimetype || null;
    details.pairedVideoSize = item.pairedVideoSize || 0;
    if (item.pairedVideoFilename) details.pairedVideoFilename = item.pairedVideoFilename;
  }
  if (item.hash) details.hash = item.hash;

  return {
    url: urlPrefix + '/' + item.originalKey,
    compressUrl:
      (mediaKind === 'image' || mediaKind === 'livePhoto') && item.compressedKey
        ? urlPrefix + '/' + item.compressedKey
        : null,
    posterUrl: mediaKind === 'video' && item.posterKey ? urlPrefix + '/' + item.posterKey : null,
    details,
  };
}

export async function finalizeAttachmentUploads(
  input: {
    userId: string;
    scopes: string[];
    noteId?: string;
    attachments?: FinalizeAttachmentInput[];
  },
  dependencyOverrides: Partial<FinalizeAttachmentDependencies> = {}
) {
  const dependencies = { ...defaultDependencies, ...dependencyOverrides };
  const storageConfig = dependencies.requireStorageAvailable();
  const uploadPolicy = await dependencies.getAttachmentUploadPolicy(input.userId);
  if (!uploadPolicy.canUploadAttachments)
    throw new Error(attachmentErrors.capabilityAttachmentUpload);

  assertFinalizeInput(input.attachments);
  assertLivePhotoFinalizeBatch(input.attachments);
  const prefix = 'users/' + input.userId + '/';
  const invalid = input.attachments.find(
    (item) =>
      !item.originalKey?.startsWith(prefix) ||
      (item.compressedKey !== undefined && !item.compressedKey.startsWith(prefix)) ||
      (item.posterKey !== undefined && !item.posterKey.startsWith(prefix)) ||
      (item.pairedVideoKey !== undefined && !item.pairedVideoKey.startsWith(prefix))
  );
  if (invalid) throw new Error(attachmentErrors.objectKeyInvalid);
  input.attachments.forEach((item) =>
    validateAttachmentPayload(item, uploadPolicy.maxVideoUploadSizeMB)
  );

  const hasVideo = finalizeInputIncludesVideo(input.attachments);
  if (hasVideo && !input.scopes.includes('video:upload'))
    throw new Error(attachmentErrors.insufficientVideoUpload);
  if (hasVideo && !uploadPolicy.canUploadVideo)
    throw new Error(attachmentErrors.capabilityVideoUpload);

  const validAttachments = await collectValidAttachments(
    input.attachments,
    dependencies.checkObjectExists
  );
  if (input.noteId) {
    const currentAttachments = await dependencies.getAttachmentDetailsByRoteId(input.noteId);
    const pendingAttachments = validAttachments.map((item) => ({
      details: {
        key: item.originalKey,
        mimetype: item.mimetype || null,
        mediaKind: inferAttachmentMediaKind({
          mediaKind: item.mediaKind,
          mimetype: item.mimetype || null,
          compressedKey: item.compressedKey,
          posterKey: item.posterKey,
          pairedVideoKey: item.pairedVideoKey,
        }),
        compressKey: item.compressedKey,
        posterKey: item.posterKey,
        pairedVideoKey: item.pairedVideoKey,
      },
    }));
    validateRoteAttachmentDetails(
      mergeUniqueRoteAttachmentDetails(currentAttachments, pendingAttachments)
    );
  }

  for (const item of validAttachments) {
    const mediaKind = inferAttachmentMediaKind({
      mediaKind: item.mediaKind,
      mimetype: item.mimetype,
      pairedVideoKey: item.pairedVideoKey,
      key: item.originalKey,
    });
    let detectedContentType: Awaited<ReturnType<typeof detectStoredImageContentTypeByKey>> = null;
    if (mediaKind === 'image' || mediaKind === 'livePhoto') {
      try {
        detectedContentType = await dependencies.detectStoredImageContentTypeByKey(
          item.originalKey
        );
      } catch (error) {
        const reason = error instanceof Error ? error.message : String(error);
        throw new Error(`Failed to inspect uploaded image ${item.originalKey}: ${reason}`);
      }

      if (detectedContentType && detectedContentType !== item.mimetype?.toLowerCase()) {
        // eslint-disable-next-line no-console
        console.info(
          `[attachment-content-type] status=corrected originalKey=${item.originalKey} declared=${item.mimetype ?? 'missing'} detected=${detectedContentType}`
        );
        item.mimetype = detectedContentType;
      }
    }

    const requiresHeicBrowserCover =
      detectedContentType === 'image/heic' ||
      (detectedContentType === null && isHeicLikeUpload(item));
    if (mediaKind === 'livePhoto') {
      if (requiresHeicBrowserCover) {
        const cover = await dependencies.ensureHeicBrowserCover(item.originalKey);
        item.compressedKey = cover.key;
      } else {
        item.compressedKey = item.originalKey;
      }
    } else if (mediaKind === 'image' && requiresHeicBrowserCover && !item.compressedKey) {
      const cover = await dependencies.ensureHeicBrowserCover(item.originalKey);
      item.compressedKey = cover.key;
    }
  }

  const uploads = validAttachments.map((item) => toUploadResult(storageConfig.urlPrefix, item));
  const finalized = await dependencies.upsertAttachmentsByOriginalKey(
    input.userId,
    input.noteId,
    uploads
  );
  validAttachments.forEach((item, index) => {
    if (!isHeicLikeUpload(item)) return;
    const stored = finalized[index] as { id?: string; compressUrl?: string } | undefined;
    // eslint-disable-next-line no-console
    console.info(
      `[heic-browser-cover] status=writeback originalKey=${item.originalKey} outputKey=${item.compressedKey} attachmentId=${stored?.id ?? 'unknown'} result=${stored?.compressUrl ? 'updated' : 'missing-compress-url'}`
    );
  });
  return finalized;
}
