# 此docker-compose文件为后端部署示例

version: "3.8"

services:
  roteMongodbRS:
    image: mongo:5
    restart: always
    ports:
      - "27017"
    volumes:
      - ./data/mongodb:/data/db
    command: ["mongod", "--replSet", "rs0"]
    networks:
      - backendNetwork

  roteMongodbSetup:
    image: mongo:5
    depends_on:
      - roteMongodbRS
    restart: on-failure
    entrypoint:
      - /bin/bash
      - -c
      - |
        mongo --host roteMongodbRS:27017 --eval 'rs.status().ok ? null : rs.initiate({
          _id: "rs0",
          members: [
            {_id: 0, host: "roteMongodbRS:27017"}
          ]
        })' && mongo --host roteMongodbRS:27017 --eval 'while (! db.hello().isWritablePrimary ) sleep(1000); db = db.getSiblingDB("Rote"); db.getCollectionNames().includes("Rote") ? 0 : db.createCollection("Rote");'
    networks:
      - backendNetwork

  rotebackend:
    image: rabithua/rotebackend:latest
    depends_on:
      - roteMongodbRS
      - roteMongodbSetup
    container_name: rotebackend
    environment:
      # 添加web端域名到这里，避免跨域问题
      - CROS=http://localhost:3000,chrome-extension://cahpbdbfdfnmoachkjmcfgbbnmjcbpej
      - DATABASE_URL=mongodb://roteMongodbRS:27017/Rote?directConnection=true&serverSelectionTimeoutMS=2000
      - SESSION_SECRET=RoteByRabithuaPrd

      # cloudflare r2储存桶配置
      - R2_BUCKET=rotedemo
      - R2_ACCOUNT_ID=9a7e130cdaa8a057ae7869e2f7782d54
      - R2_ACCESS_KEY_ID=071233d53a1c4fde9018fd0940d7d408
      - R2_SECRET_KEY_ID=f35b0e2f4d5fa38905e50324a0d804830a471da4533919c7700fba157c02f378
      - R2_URL_PREFIX=r2demo.rote.ink

      # webpush需要生成VAPID
      # - VAPID_PUBLIC_KEY=BDYfGAEoJIxxxFfy8ZX4Gw1YdxxxxxxxxxxxX-fPUFWVjAmPKwwWikLAmvYDh5ht1Mi8ac_qFFrc8Oz4g
      # - VAPID_PRIVATE_KEY=25IK6YYxWFhoE1ntALVFpxxxxxxxxxGb4W9bGzlMaZ4I
    ports:
      - 3001:3000
    restart: always
    networks:
      - backendNetwork

  roteweb:
    image: rabithua/roteweb:latest
    depends_on:
      - roteMongodbRS
      - roteMongodbSetup
      - rotebackend
    container_name: roteweb
    environment:
      # 如果为后端api配置反向代理，可以使用 http://[IP]:3001
      - REACT_APP_BASEURL_PRD=http://localhost:3001
      # 如果后端配置了R2储存桶，可以修改为true开启文件上传功能
      - REACT_APP_ALLOW_UPLOAD_FILE=true
      # 生成sitemap需要用到，为前端web部署的域名
      # - URL=https://rote.ink
      # web-push相关配置，不懂可以注释掉
      # - VAPID_PUBLIC_KEY=BFKK3FRRIGK8ZjtwjalylFZbiFHuqwEo8wlJ1O0cjejKK7czee0PDd1pU51RcanA7YuWFUTxFluR6ERhxLIrWSc

    ports:
      - 3000:3000
    restart: always
    networks:
      - backendNetwork

networks:
  backendNetwork:
    driver: bridge
